s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
s=set()
a =(int(input("enter the number: ")))
s.add(int(a))
print(s)